//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_Persons
    {
        public decimal IDSE_Person { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Gender { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<byte> Employed { get; set; }
        public string CivilStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public byte Invalidated { get; set; }
    }
}
