//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_Users
    {
        public int IDSE_User { get; set; }
        public Nullable<decimal> IDSE_UserPersonalInfo { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Invalidated { get; set; }
    
        public virtual SE_UserPersonalInfo SE_UserPersonalInfo { get; set; }
    }
}
